rsvp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('events.urls')),
    # Sitemap
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

events/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models.signals import pre_save
from rsvp.utils import unique_slug_generator
from optimized_image.fields import OptimizedImageField
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.


# BASE MODELS -------------------------------------------------------------------------

# Base Event Agenda
class BaseEventAgenda(models.Model):
    lineup = models.CharField(
        max_length=100, help_text="Agenda title.")
    date = models.DateField(blank=True, null=True,
                            help_text="Date of occurrence.")
    start_time = models.TimeField(
        blank=True, null=True, help_text="Time of occurrence.")
    end_time = models.TimeField(
        blank=True, null=True, help_text="Estimated end time.")
    created = models.DateTimeField(
        default=timezone.now, help_text="Date of creation.")
    modified = models.DateTimeField(
        auto_now=True, help_text="Occurrence of the most recent update to this subsection.")

    def __str__(self):
        return self.lineup

    class Meta:
        abstract = True


# Base Event
class BaseEvent(models.Model):
    title = models.CharField(max_length=100, help_text="Event title.")
    slug = models.SlugField(max_length=150, unique=True,
                            help_text="Event URL.")
    status_choices = (
        ('Open', 'Open'),
        ('Closed', 'Closed')
    )
    status = models.CharField(
        max_length=6, choices=status_choices, default='Open', help_text="Status of Event.")
    booking_deadline = models.DateField(
        blank=False, null=False, help_text="Event deadline.")
    availability_choices = (
        ('Unlimited', 'Unlimited'),
        ('Limited', 'Limited')
    )
    availability = models.CharField(
        max_length=10, choices=availability_choices, default='Unlimited', help_text="If event is space limited.")
    slots = models.IntegerField(
        null=True, blank=True, help_text="Number of slots if availability is marked as 'limited'.")
    description = models.TextField(
        max_length=1000, help_text="Event description.")
    important_note = models.TextField(
        null=True, blank=True, help_text="Important information or notes regarding the event.")
    start_date = models.DateTimeField(help_text="Event start date.")
    end_date = models.DateTimeField(
        blank=True, null=True, help_text="Event end date, if any.")
    created = models.DateTimeField(
        default=timezone.now, help_text="Date of creation.")
    modified = models.DateTimeField(
        auto_now=True, help_text="Occurrence of the most recent update to this subsection.")

    def booking_deadline_has_passed(self):
        return self.booking_deadline > datetime.date.today()

    def is_limited(self):
        return self.availability == 'Limited'

    def is_full(self):
        return self.is_limited and GeneralEventBooking.adult_bookings.count() >= self.slots

    def is_closed_for_bookings(self):
        return True if self.is_full() or self.booking_deadline_has_passed() else False

    def __str__(self):
        return self.title

    class Meta:
        abstract = True


# Base Event Form Model
class BaseEventBooking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(
        max_length=50, help_text="Your first name.")
    last_name = models.CharField(
        max_length=50, help_text="Your last name.")
    email = models.EmailField(max_length=50, help_text="Main e-mail address.")
    phone_number = PhoneNumberField(
        max_length=15, help_text="Phone number, mobile or landline.")
    booking_date = models.DateTimeField(
        default=timezone.now, help_text="Date of creation.")
    modified_date = models.DateTimeField(
        auto_now=True, help_text="Occurrence of the most recent update to this booking.")

    def __str__(self):
        return self.first_name + self.last_name

    class Meta:
        abstract = True


# GENERAL EVENTS ----------------------------------------------------------------------

# General Event Agenda
class GeneralEventAgenda(BaseEventAgenda):
    general_event = models.ForeignKey('GeneralEvent', on_delete=models.CASCADE)

    class Meta():
        verbose_name = 'General event agenda'
        verbose_name_plural = 'General event Agenda'


# General Event
class GeneralEvent(BaseEvent):
    image = OptimizedImageField(
        upload_to='events/images/general_events/', blank=False, null=False, help_text="Event cover image.")
    adult_fee = models.DecimalField(
        max_length=20, max_digits=6, decimal_places=2, default='0', help_text="Event fee for Adults, per slot.")
    kids_fee = models.DecimalField(
        max_length=20, max_digits=6, decimal_places=2, default='0', help_text="Event fee for Kids, per slot.")

    class Meta():
        verbose_name = 'General Event'
        verbose_name_plural = 'General Events'


# General Event Form Model
class GeneralEventBooking(BaseEventBooking):
    event = models.ForeignKey(
        GeneralEvent, default=None, null=True, on_delete=models.CASCADE)
    adult_bookings_choices = (
        ('0', '0'),
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
        ('9', '9'),
        ('10', '10')
    )
    adult_bookings = models.CharField(
        max_length=3, choices=adult_bookings_choices, default='0', help_text="Number of Adults.")
    children_bookings_choices = (
        ('0', '0'),
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
        ('9', '9'),
        ('10', '10')
    )
    children_bookings = models.CharField(
        max_length=3, choices=children_bookings_choices, default='0', help_text="Number of Children.")

    class Meta():
        verbose_name = 'Bookings'
        verbose_name_plural = 'Bookings'


# YOUTH EVENTS ------------------------------------------------------------------------

# Youth Event Agenda
class YouthEventAgenda(BaseEventAgenda):
    youth_event = models.ForeignKey('YouthEvent', on_delete=models.CASCADE)

    class Meta():
        verbose_name = 'Youth event agenda'
        verbose_name_plural = 'Youth event Agenda'


# Youth Event
class YouthEvent(BaseEvent):
    image = OptimizedImageField(upload_to='events/images/youth_events/',
                                blank=False, null=False, help_text="Event cover image.")
    age_group_choices = (
        ('All', 'All'),
        ('Young Adults', 'Young Adults'),
        ('Teens', 'Teens'),
        ('Kids', 'Kids')
    )
    age_group = models.CharField(
        max_length=50, choices=age_group_choices, default='All', help_text="Age group in which Event is intended for.")
    fee = models.DecimalField(
        max_length=20, max_digits=6, decimal_places=2, default='0', help_text="Event Fee per slot.")

    class Meta():
        verbose_name = 'Youth Event'
        verbose_name_plural = 'Youth Events'


# Youth Event Form Model
class YouthEventBooking(BaseEventBooking):
    event = models.ForeignKey(YouthEvent, default=None,
                              null=True, on_delete=models.CASCADE)
    bookings_choices = (
        ('0', '0'),
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8'),
        ('9', '9'),
        ('10', '10')
    )
    bookings = models.CharField(
        max_length=50, choices=bookings_choices, default='0', help_text="Number of attendees.")

    class Meta():
        verbose_name = 'Bookings'
        verbose_name_plural = 'Bookings'


# OTHER --------------------------------------------------------------------------------

# Slug


def slug_save(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance, instance.title)


def save(self, *args, **kwargs):
    self.s = slugify(self.q)
    super(Test, self).save(*args, **kwargs)


pre_save.connect(slug_save, sender=GeneralEvent)
pre_save.connect(slug_save, sender=YouthEvent)

templates/events/events_booking/general_events/general_event_complete.html
{% extends 'events/root.html' %} {% block title %}Booking Complete{% endblock %} {% block content %}
{% load static %}

{# Breadcrumbs #}
<div class="container-fluid">
    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'events' %}">Events</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'general_events' %}">General Events</a></li>
                    <li class="breadcrumb-item"><a
                            href="{% url 'general_events_booking' slug=event.slug %}">{{ event.title }}</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">Booking Complete</li>
                </ol>
                <hr>
            </nav>
        </div>
    </div>
</div>

{# Banner #}
<div class="container-fluid">
    <div class="row my-5">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <h2 class="display-4">Booking Complete</h2>
        </div>
    </div>
</div>

{# Options #}
<div class="container-fluid">
    <div class="row my-5">
        <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-12">
            <div class="form-group">
                <button onclick="window.print()" class="btn btn-lg btn-block btn-outline-primary">Download
                    Receipt</button>
            </div>
        </div>
        <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-12">
            <div class="form-group">
                <a href="{% url 'general_events_user_bookings_list' %}"
                    class="btn btn-lg btn-block btn-outline-primary">Manage
                    Bookings</a>
            </div>
        </div>
        <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-12">
            <div class="form-group">
                <a href="{% url 'events' %}" class="btn btn-lg btn-block btn-outline-primary">View More Events</a>
            </div>
        </div>
    </div>
</div>

{# Divider #}
<div class="container-fluid">
    <div class="row my-5">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <hr>
        </div>
    </div>
</div>

{# Payment info #}
<div class="container-fluid">
    <div class="row mt-4">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <p>You're booking has been processed.</p>
            <p>Please note, all payments (if any) are done off-line to avoid unnecessary charges and confusion. Ensure
                you pay in advance or on the day of the event.</p>
        </div>
    </div>
</div>

{# Divider #}
<div class="container-fluid">
    <div class="row my-5">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <hr>
        </div>
    </div>
</div>

{# Booking Info #}
<div class="container-fluid">
    <div class="row mt-4">
        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
            <h4 class="font-weight-bold">Booking Information:</h4>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
            <div class="form-group">
                <ul class="list-group">
                    <li class="list-group-item bg-light">First Name:</li>
                    <li class="list-group-item">{{ event_booking.first_name }}</li>
                </ul>
            </div>
        </div>
        <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
            <div class="form-group">
                <ul class="list-group">
                    <li class="list-group-item bg-light">Last Name:</li>
                    <li class="list-group-item">{{ event_booking.last_name }}</li>
                </ul>
            </div>
        </div>
        <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
            <div class="form-group">
                <ul class="list-group">
                    <li class="list-group-item bg-light">E-mail:</li>
                    <li class="list-group-item">{{ event_booking.email }}</li>
                </ul>
            </div>
        </div>
        <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
            <div class="form-group">
                <ul class="list-group">
                    <li class="list-group-item bg-light">Phone Number:</li>
                    <li class="list-group-item">{{ event_booking.phone_number }}</li>
                </ul>
            </div>
        </div>
        <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
            <div class="form-group">
                <ul class="list-group">
                    <li class="list-group-item bg-light">Event Booked:</li>
                    <li class="list-group-item">{{ event.title }}</li>
                </ul>
            </div>
        </div>
        <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
            <div class="form-group">
                <ul class="list-group">
                    <li class="list-group-item bg-light">Booking Date:</li>
                    <li class="list-group-item">{{ event_booking.booking_date }}</li>
                </ul>
            </div>
        </div>
        <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
            <div class="form-group">
                <ul class="list-group">
                    <li class="list-group-item bg-light">Adult Bookings:</li>
                    <li class="list-group-item">{{ event_booking.adult_bookings }}</li>
                </ul>
            </div>
        </div>
        <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
            <div class="form-group">
                <ul class="list-group">
                    <li class="list-group-item bg-light">Kides Bookings:</li>
                    <li class="list-group-item">{{ event_booking.children_bookings }}</li>
                </ul>
            </div>
        </div>
        <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
            <div class="form-group">
                <ul class="list-group">
                    <li class="list-group-item bg-light">Total Owed:</li>
                    <li class="list-group-item" id="total_fee"></li>
                </ul>
            </div>
        </div>
    </div>
</div>

{# Divider #}
<div class="container-fluid">
    <div class="row my-5">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <hr>
        </div>
    </div>
</div>

{# Event Info #}
<div class="container-fluid">
    <div class="row mt-4">
        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
            <h4 class="font-weight-bold">Event Information:</h4>
        </div>
    </div>
    <div class="row mt-4">
        <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
            <div class="form-group">
                <ul class="list-group">
                    <li class="list-group-item bg-light">Event Start Date:</li>
                    <li class="list-group-item">{{ event.start_date }}</li>
                </ul>
            </div>
        </div>
        {% if event_booking.end_date %}
        <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
            <div class="form-group">
                <ul class="list-group">
                    <li class="list-group-item bg-light">Event End Date:</li>
                    <li class="list-group-item">{{ event.end_date }}</li>
                </ul>
            </div>
        </div>
        {% endif %}
        <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
            <div class="form-group">
                <ul class="list-group">
                    <li class="list-group-item bg-light">Adult Fee:</li>
                    <li class="list-group-item">€ {{ event.adult_fee }}</li>
                </ul>
            </div>
        </div>
        <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
            <div class="form-group">
                <ul class="list-group">
                    <li class="list-group-item bg-light">Kides Fee:</li>
                    <li class="list-group-item">€ {{ event.kids_fee }}</li>
                </ul>
            </div>
        </div>
    </div>
</div>

{# Total Owed Calculation #}
{% include "events/include/general_events/total_cost.html" %}

{% endblock %}

templates/events/events_booking/general_events/general_event_detail.html
{% extends 'events/root.html' %} {% block title %}{{ event.title }}{% endblock %} {% block content %}
{% load static %}

{# Breadcrumbs #}
<div class="container-fluid">
  <div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
          <li class="breadcrumb-item"><a href="{% url 'events' %}">Events</a></li>
          <li class="breadcrumb-item"><a href="{% url 'general_events' %}">General Events</a></li>
          <li class="breadcrumb-item active" aria-current="page">{{ event.title }}</li>
        </ol>
        <hr>
      </nav>
    </div>
  </div>
</div>

{# Banner #}
<div class="container-fluid">
  <div class="row my-5">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
      <h2 class="display-4">{{ event.title }}</h2>
    </div>
  </div>
</div>

{# Image #}
{% if event.image %}
<div class="container-fluid">
  <div class="row mt-4">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
      <img src="{% static 'global/images/placeholders/image-placeholder.jpg' %}" data-src="{{ event.image.url }}"
        loading="lazy" alt="{{ event.image.name }}" class="lazy img" width="100%">
    </div>
  </div>
</div>
{% endif %}

{# Divider #}
<div class="container-fluid">
  <div class="row my-5">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
      <hr>
    </div>
  </div>
</div>

{# Event Info #}
<div class="container-fluid">
  <div class="row mt-4">
    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
      <h4 class="font-weight-bold">Event Information:</h4>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
      <div class="form-group">
        <ul class="list-group">
          <li class="list-group-item bg-light">Status:</li>
          {% if event.status == 'Open' %}
          <li class="list-group-item text-success">{{ event.status }}</li>
          {% else %}
          <li class="list-group-item text-danger">{{ event.status }}</li>
          {% endif %}
        </ul>
      </div>
    </div>
    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
      <div class="form-group">
        <ul class="list-group">
          <li class="list-group-item bg-light">Booking Deadline:</li>
          <li class="list-group-item">{{ event.booking_deadline }}</li>
        </ul>
      </div>
    </div>
    {% if event.available_slots %}
    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
      <div class="form-group">
        <ul class="list-group">
          <li class="list-group-item bg-light">Available Slots:</li>
          <li class="list-group-item">{{ event.available_slots }}</li>
        </ul>
      </div>
    </div>
    {% endif %}
    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
      <div class="form-group">
        <ul class="list-group">
          <li class="list-group-item bg-light">Event Start Date:</li>
          <li class="list-group-item">{{ event.start_date }}</li>
        </ul>
      </div>
    </div>
    {% if event.end_date %}
    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
      <div class="form-group">
        <ul class="list-group">
          <li class="list-group-item bg-light">Event End Date:</li>
          <li class="list-group-item">{{ event.end_date }}</li>
        </ul>
      </div>
    </div>
    {% endif %}
    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
      <div class="form-group">
        <ul class="list-group">
          <li class="list-group-item bg-light">Adult Fee:</li>
          <li class="list-group-item">€ {{ event.adult_fee }}</li>
        </ul>
      </div>
    </div>
    <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
      <div class="form-group">
        <ul class="list-group">
          <li class="list-group-item bg-light">Kides Fee:</li>
          <li class="list-group-item">€ {{ event.kids_fee }}</li>
        </ul>
      </div>
    </div>
  </div>
</div>

{# Divider #}
<div class="container-fluid">
  <div class="row my-5">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
      <hr>
    </div>
  </div>
</div>

{# Description #}
{% if event.description %}
<div class="container-fluid">
  <div class="row mt-4">
    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
      <h4 class="font-weight-bold">Description:</h4>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
      <p>{{ event.description }}</p>
    </div>
  </div>
</div>
{% endif %}

{# Divider #}
{% if event.generaleventagenda_set.all %}
<div class="container-fluid">
  <div class="row my-5">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
      <hr>
    </div>
  </div>
</div>
{% endif %}

{# Agenda #}
{% if event.generaleventagenda_set.all %}
<div class="container-fluid">
  <div class="row mt-4">
    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
      <h4 class="font-weight-bold">Agenda:</h4>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
      <p>Please keep in mind, Agenda is subject to change.</p>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
      <div class="table-responsive">
        <table class="table table-hover">
          <thead class="thead-light">
            <tr>
              <th scope="col" colspan="4">Lineup</th>
              <th scope="col" colspan="4">Date</th>
              <th scope="col" colspan="4">Start Time</th>
              <th scope="col" colspan="4">End Time</th>
            </tr>
          </thead>
          <tbody>
            {% for event in event.generaleventagenda_set.all %}
            <tr>
              <td colspan="4">{{ event.lineup }}</td>
              <td colspan="4">{{ event.date }}</td>
              <td colspan="4">{{ event.start_time|time:"H:i" }}</td>
              <td colspan="4">{{ event.end_time|time:"H:i" }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endif %}

{# Divider #}
{% if event.important_note %}
<div class="container-fluid">
  <div class="row my-5">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
      <hr>
    </div>
  </div>
</div>
{% endif %}

{# Important Note #}
{% if event.important_note %}
<div class="container-fluid">
  <div class="row mt-4">
    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
      <h4 class="font-weight-bold">Important Note:</h4>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
      <p>{{ event.important_note }}</p>
    </div>
  </div>
</div>
{% endif %}

{# Divider #}
<div class="container-fluid">
  <div class="row my-5">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
      <hr>
    </div>
  </div>
</div>

{# Form #}
<div class="container-fluid">
  <div class="row mt-4">
    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
      <h4 class="font-weight-bold">Booking:</h4>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
      <p>Please note, we do not process payments online. All payments are done off-line only to avoid unnecessary
        charges and confusion.</p>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
      {% if event.status == 'Open' %}
      <form method="post"
        oninput="totalprice.value=parseInt(id_adult_bookings.value*{{ event.adult_fee }})+parseInt(id_children_bookings.value*{{ event.kids_fee }})">

        {% csrf_token %}
        {% load crispy_forms_tags %}

        <div class="form-row my-2">
          <div class="form-group col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
            {{ form.first_name|as_crispy_field }}
          </div>
          <div class="form-group col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
            {{ form.last_name|as_crispy_field }}
          </div>
        </div>
        <div class="form-row my-2">
          <div class="form-group col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
            {{ form.email|as_crispy_field }}
          </div>
          <div class="form-group col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
            {{ form.phone_number|as_crispy_field }}
          </div>
        </div>
        <div class="form-row my-2">
          <div class="form-group col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
            {{ form.adult_bookings|as_crispy_field }}
          </div>
          <div class="form-group col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
            {{ form.children_bookings|as_crispy_field }}
          </div>
        </div>

        <div class="row mt-2">
          <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
            <div class="form-group">
              <label for="totalprice">Total Price:</label>
              <div class="input-group">
                <span class="input-group-prepend">
                  <span class="input-group-text">€</span>
                </span>
                <output name="totalprice" for="id_adult_bookings id_children_bookings" class="form-control"></output>
                <span class="input-group-append">
                  <span class="input-group-text">.00</span>
                </span>
              </div>
            </div>
          </div>
        </div>

        <div class="row mt-5">
          <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
            <div class="form-group">
              <button type="reset" class="btn btn-lg btn-block btn-danger">Clear</button>
            </div>
          </div>
          <div class="col-xl-3 col-lg-3 col-md-6 col-sm-12 col-12">
            <div class="form-group">
              <button type="submit" class="btn btn-lg btn-block btn-primary">Submit</button>
            </div>
          </div>
        </div>

      </form>
      {% else %}
      <div class="card bg-info text-dark font-weight-bold">
        <div class="card-body py-5">
          <p class="card-text">
            <i class="fal fa-exclamation-triangle font-weight-bold  mr-2"></i>
            Bookings for this event are now Closed.
          </p>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}